# AppCenter CLI
#
# Triggers are configured in the UI

jobs:
- job:

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'Install and build'

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance (PR)
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'Medium'
      failOnAlert: true
      ignoreDirectories: '$(COMPONENT_GOVERNANCE_IGNORE_DIRS)'
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))

  - task: ComponentGovernanceComponentDetection@0
    displayName: Component Governance (CI)
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'Medium'
      failOnAlert: false
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  - script: |
      npm test
    displayName: 'Run tests'

  - script: |
      npm pack
    displayName: 'Package for npm release'

  - task: DeleteFiles@1
    inputs:
      contents: node_modules

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: true
      archiveType: 'tar'
      archiveFile: '$(Build.ArtifactStagingDirectory)/npm/$(Build.BuildId).tgz'
      replaceExistingArchive: true
      verbose: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/npm'
      ArtifactName: 'npm'
    displayName: 'Publish npm artifact'